name: Build and push image

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*.**' # Push events to matching v*, i.e. v1.0, v20.15.10
# on:
#  release:
#    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          image: lsilvatux/github-runner-image
          tag: ${{ github.ref }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
