name: Build and push image

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*.**' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3 | cut -d v -f 2)
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push protoc image
        id: docker_build_protoc
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.protoc
          push: true
          tags: hurb/github-runner-image-protoc:${{ steps.get_version.outputs.VERSION }}, hurb/github-runner-image-protoc:latest
      - name: Build and push main image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: hurb/github-runner-image:${{ steps.get_version.outputs.VERSION }}, hurb/github-runner-image:latest          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}